### ISSUE TITLE
disabling Security hub does not appear to be working

### ISSUE THREAD

**Issue by frankscalzo** [awslabs/landing-zone-accelerator-on-aws#147]
**Describe the bug**
I have deployed security hub with controls i have a few controls that i need to not be on so i added them to the disabled tab but i am still showing the controls enabled and its lowing my score.

I just did a redeploy with the NIST. in front of NIST specific  controls to see if that works as well but at the same time any of the others do not show in the disabled list 

![Screenshot 2023-05-11 at 10 40 42 AM](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/10548647/165ac1f2-d0e0-4653-9705-f39413cd30a3)

**To Reproduce**
here is the code i have in the LZ config 
 securityHub:
    enable: true
    regionAggregation: 
    snsTopicName: Security
    notificationLevel: HIGH
    excludeRegions: []
    standards:
      - name: AWS Foundational Security Best Practices v1.0.0
        # https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html
       deploymentTargets:
         organizationalUnits:
           -  Root
        enable: true
        controlsToDisable:
          - IAM.6
          - CloudFormation.1
          - Config.1
      
      - name: PCI DSS v3.2.1
        # https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-pci-controls.html
        enable: false 
        controlsToDisable:
          - PCI.IAM.6
          - PCI.IAM.4
          - PCI.CloudFormation.1
          -	PCI.Config.1

      - name: CIS AWS Foundations Benchmark v1.4.0
        # https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-cis-controls.html
        deploymentTargets:
         organizationalUnits:
           -  Root
        enable: true
        controlsToDisable:
          - CIS.1.17
          - CIS.1.16
          - CIS.1.14
          - CIS.1.6
          - CIS.Config.1
          
      - name: NIST Special Publication 800-53 Revision 5
        # https://docs.aws.amazon.com/securityhub/latest/userguide/nist-standard.html
        deploymentTargets:
         organizationalUnits:
           -  Root
        enable: true
        controlstoDisable:
          - IAM.6
          - CloudFormation.1
          -	Config.1

**Expected behavior**
i was expecting them to be disabled and also not show as an issue

**Comment by erwaxler** [comment]
@frankscalzo Thank you for identifying this! I have created an issue for our team to investigate this behavior, I will update this issue when I have more information.

**Comment by frankscalzo** [comment]
> @frankscalzo Thank you for identifying this! I have created an issue for our team to investigate this behavior, I will update this issue when I have more information.

@erwaxler  was anyone able to find out anything maybe i am doing it wrong does the NIST have to have NIST. in front of it since i see PCI and CIS has that called out in the samples

**Comment by erwaxler** [comment]
@frankscalzo We have been able to replicate this behavior in an internal environment, the team is working on a fix to include in the next major release.

**Comment by erwaxler** [comment]
@frankscalzo Something just caught my eye, can you try changing `controlstoDisable:` to `controlsToDisable:` with a capital 'T' in "To." I think this may simply be a case of incorrect capitalization in our best practices. I'm making that update to our best-practices configuration, but changing that capitalization may be all it takes to get this working in your environment today.

**Comment by frankscalzo** [comment]
@erwaxler i am thinking this has to do with Aggregation i found a page that talked about the codes being handled differently since the IAM.6 is not going away in the ignore even with the cap issue resolved 

https://docs.aws.amazon.com/securityhub/latest/userguide/asff-changes-consolidation.html#securityhub-findings-format-changes-ids-titles

i noticed that the only one still showing is AWS v1.4 i9t looks like see attached 

![image](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/10548647/fe65f275-b0be-4003-9730-d1faec7560da)

Also noted from the above link the control path changes 

![image](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/10548647/5570ce18-cae3-48a1-9a4c-d379dc052de2)


here is the revised 

    standards:
      - name: AWS Foundational Security Best Practices v1.0.0
        # https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html
        deploymentTargets:
         organizationalUnits:
           -  Root
        enable: true
        controlsToDisable:
          - IAM.6
          - CloudFormation.1
          - Config.1
          - KMS.3
      
      - name: PCI DSS v3.2.1
        # https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-pci-controls.html
        enable: true 
        controlsToDisable:
          - PCI.IAM.6
          - PCI.IAM.4
          - PCI.CloudFormation.1
          -	PCI.Config.1

      - name: CIS AWS Foundations Benchmark v1.4.0
        # https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-cis-controls.html
        deploymentTargets:
         organizationalUnits:
           -  Root
        enable: true
        controlsToDisable:
          - IAM.6
          - Config.1
          - KMS.3
          - IAM.1.14
          
      - name: NIST Special Publication 800-53 Revision 5
        # https://docs.aws.amazon.com/securityhub/latest/userguide/nist-standard.html
        deploymentTargets:
         organizationalUnits:
           -  Root
        enable: true
        controlsToDisable:
          - IAM.6
          - CloudFormation.1
          -	Config.1
          - EC2.23
          - KMS.3

**Comment by bakharzy** [comment]
Hi @erwaxler 
I am having the same issue for disabling some SecurityHub controls. Even though I disabled the controls in LZA, I still notice the controls are enabled!
I noticed in the source code something strange:
https://github.com/awslabs/landing-zone-accelerator-on-aws/blob/1614a01824c5a43f97fadfb8ec0c3627a0f343dd/source/packages/%40aws-accelerator/config/lib/security-config.ts#L1001

```
   * (OPTIONAL) An array of control names to be enabled for the given security standards
   */
  readonly controlsToDisable: string[] = [];
```
In the comment, it is mentioned an array of controls to be **enabled**. Could be that the actual implementation in enabling the controls we give in the array of controlsToDisable? 

btw, my current version of LZA is: release/v1.3.2

**Comment by erwaxler** [comment]
Hi @bakharzy, thanks for identifying that, but that is a typo and not the implementation. That array is used to determine which controls to disable, I'll create a ticket to get that language updated. Regarding the original issue, we have implemented a fix that will be included in our next release, expected to be available in the next few weeks.

**Comment by awsclemj** [comment]
Hello,

A fix for this issue has been included in our [v1.5.0 release](https://github.com/awslabs/landing-zone-accelerator-on-aws/releases/tag/v1.5.0). I will be closing this issue as resolved. Thanks for your support of Landing Zone Accelerator!

**Comment by bakharzy** [comment]
@awsclemj 
I am using the version 1.5.1 and can confirm that this bug still exists.

**Comment by bpcue** [comment]
> Hello,
> 
> A fix for this issue has been included in our [v1.5.0 release](https://github.com/awslabs/landing-zone-accelerator-on-aws/releases/tag/v1.5.0). I will be closing this issue as resolved. Thanks for your support of Landing Zone Accelerator!

I am running 1.50 and this issue still exists.

**Comment by Thomas-McKanna** [comment]
Any update on this? It still seems to be a problem in 1.6.

**Comment by bakharzy** [comment]
@awsclemj can you please open the issue again?

**Comment by Thomas-McKanna** [comment]
Here's some more context.

When I look at the overview page for a standard, the controls I want to be disabled _do not_ appear in the Disabled section:

![image](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/22783091/b921b9e5-be9a-4de9-9bdd-e41c193cd37a)

But when I click on an individual control and go to its detail page, it looks like the control is in fact disabled, but for some reason also shows it as failing:

<img width="1496" alt="image" src="https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/22783091/acd81640-9ce2-4956-9fea-d10b399c987e">

I also notice that the failed findings all seem to be from before the control was disabled. So maybe AWS lists the control as failing if there are any remaining findings, even after disabling the control.

I will try suppressing the findings for the controls I disabled and see if that causes the UI to list the control as disabled.

**Comment by bhkhatri221** [comment]
Hi @Thomas-McKanna , Thank you for the update. Based on the information provided, it appears that the control to disable the feature is functioning correctly, as evidenced by the screenshot showing "Control disabled by Accelerator." However, it seems that Security Hub is not reflecting the changes on the dashboard. For any further questions or assistance regarding the issue with the dashboard not updating, please feel free to reach out to the Security Hub team.
