### ISSUE TITLE
Accounts closed or renamed leave records in DynamoDB

### ISSUE THREAD

**Issue by KashifSaadat** [awslabs/landing-zone-accelerator-on-aws#202]
## Describe the bug

I've stepped through official documentation or taken steps to:
1. Close an AWS Account that was provisioned via this solution
2. Renamed an AWS Account
3. Changed the root email address for an AWS Account (same user journey as 2)

In scenarios 1 and 3, the DynamoDB table `AcceleratorConfigTable` has not removed the old record for the closed account, and in the case of the root email address change an additional record has appeared in DynamoDB (the existing record with the old email address is still there).

Please could you also confirm if the below steps to **rename an account** or **change the root email address** are correct? I couldn't find this in the official documentation for this project.

## To Reproduce

**Close an Account:**
1. Login to the AWS Account where Control Tower is managed
2. Switch to the home region
3. Navigate to AWS Service Catalog and “Provisioned products”
4. Under “Access Filter”, select “Account”
5. Select the account to close
6. Under Actions (top right), choose Terminate and confirm in the pop-up
7. Wait for this to complete and disappear from Service Catalog
8. Navigate to AWS Organizations
9. Select the Account and move it to the “Suspended” OU (should have `ignore: true` in the `organization-config.yaml` for this OU)
10. Select the Account and “Close Account”
11. Update the LZA codebase and remove (or comment out) the account

**Change root email address for an Account:**
1. Update the LZA SCP for the relevant OU and ensure "iam:UpdateAccountName" is permitted: `service-control-policies/deny-X.json`
2. Login via the root credentials for the AWS Account in question
3. Navigate to: https://us-east-1.console.aws.amazon.com/billing/home#/account
4. Edit the “Account settings” and set the email address
5. Update the LZA repository and:
    1. Modify the email address: `accounts-config.yaml`
    2. Put the SCP back to original configuration if it was modified

## Expected behavior

1. The DynamoDB table `AcceleratorConfigTable` should not contain records for a closed account that has been removed from the codebase (?).
2. The DynamoDB table `AcceleratorConfigTable` should have updated the existing record of an account where the root email address has changed, rather than creating a new record.

## Extra details

- [x] Version: v1.4.1
- [x] Region: [e.g. eu-west-2]
- [ ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?

**Comment by bhkhatri221** [comment]
Hi @KashifSaadat, thank you for creating this issue! I have created an issue for our team to investigate this behavior. I will update this issue when I have more information.

Here are documents that provide additional information about renaming and closing of:
1. [Updating the AWS account name, email address, or password for the root user.](https://docs.aws.amazon.com/accounts/latest/reference/manage-acct-update-root-user.html)
2. [Closing an account.](https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/performing-administrator-tasks.html#closing-an-account)
3. [Change the name of an enrolled account.](https://docs.aws.amazon.com/controltower/latest/userguide/change-account-name.html)

**Comment by bakharzy** [comment]
I have similar issue now. 
I updated the LZA from version `1.3.2` to `1.5.0`. The stack (CloudFormation) update was successful. The installer pipeline also ran successfully, I are facing errors in the `Deploy/Security_Resources` stage of `AWSAccelerator-Pipeline`. 

`
2023-10-20 07:09:07.847 \| error \| toolkit \| Error: User: arn:aws:sts::123456780970:assumed-role/AWSAccelerator-PipelineSt-AdminCdkToolkitRole292E1-XRA7LYSN8LDF/AWSCodeBuild-f93df3ne-b8f3-46af-af54-122b001b10fc is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::111111111111:role/AWSControlTowerExecution
`

The error is complaining about AccessDenied to an account (111111111111) which is in suspended and unmanaged state. The account is in SUSPENDED OU which has ignore flag true. The account is waiting for its 90 days period to be closed permanently. Not sure why the pipeline is still picking it up. I also tried to run the pipeline from the beginning and it didn’t help.

**Extra information:**
This account was created by mistake. I was trying to rename and change email of an existing account. Let's say the existing account's name was Sandbox and using sandbox@example.com email address. To rename the account and change its email address, I modified the current information in `accounts-config.yaml`. So, I changed the name of the Sandbox to Sandbox2 and changed the email to sandbox2@example.com. I now know this was the wrong way to do these changes! The behavior of LZA was to create a new account with name Sandbox2 and the new email and leave the older Sandbox account as it. Since the new account was not needed, I followed the unmanage and close steps mentioned in LZA documentation. 

Is there any workaround to fix this issue for the short-term?

**Comment by KashifSaadat** [comment]
Hi @bakharzy, so just to check is your configuration currently in a similar state to what's described in this document (for the `Sandbox` closed account): https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/performing-administrator-tasks.html#ignoring-an-account-from-resource-provisioning

I haven't run into your case specifically, it's unusual that it is still picking up the account. You could try with backing up the record in the DynamoDB Table and dropping that specific record to see if it unblocks the pipeline, however I've not tested this so not sure what the behaviour would be.

**Comment by KashifSaadat** [comment]
@bakharzy it looks like it was a bug introduced in v1.5.0, which is now fixed in v1.5.1: https://github.com/awslabs/landing-zone-accelerator-on-aws/releases/tag/v1.5.1

**Comment by bakharzy** [comment]
Hi @KashifSaadat 
Thanks for getting back to me. Yes, I confirm that I followed those instructions to ignore the OU and the suspended account is moved to that ignored OU.
And thanks for the heads up regarding the new release. This might sort out the issue I am facing.

**Comment by alabkris** [comment]
we are still facing this issue on version 1.9, do we need to remove them manually? or is there a fix?
